using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Mail;

namespace BrotecsLateSMSReporting
{
    class EmailReport
    {
        private MailMessage message;
        private SmtpClient smtp;
        private const string emailFooter = "\n\n**\nThis mail is auto generated by Brotecs HRM System.\nPlease do not reply to this mail.\n**\n\n--------------------------\nkind regards,\nSystem Administrator\nBrotecs HRM System.\n";
        private const string serverMailAddress = "brotecs.oms@brotecs.com";
        private const string passKey = "";

        public EmailReport()
        {
            message = new MailMessage();
            smtp = new SmtpClient();
        }
        // MailAddress from = new MailAddress("murad.hasan@brotecs.com", "Murad Hasan");
        public int SendEmailReport(MailAddress form, string to, List<string> cc, string subject, string body, string msgFormat)
        {
            try
            {
                Trace.Write(string.Format("----------------------------"));
                message.To.Add(new MailAddress(to));
                Trace.Write(string.Format("To:\t{0}", to));
                Trace.Write(string.Format("CC:\t"));
                foreach (string mailAddress in cc)
                {
                    message.CC.Add(new MailAddress(mailAddress));
                    Trace.WriteLine(string.Format("\t{0}", mailAddress));
                }
                message.From = form;
                Trace.WriteLine(string.Format("From:\t{0}", message.From));
                message.Subject = subject;
                Trace.WriteLine(string.Format("Subject: {0}", message.Subject));
                message.Body = body + msgFormat + emailFooter;
                Trace.WriteLine(string.Format("Body:\n{0}", message.Body));
                Trace.Write(string.Format("----------------------------"));

                smtp.Port = 587;
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential(serverMailAddress, passKey);
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.Send(message);
                return 0;
            }
            catch (Exception ex)
            {
                Trace.WriteLine(string.Format("err: " + ex.Message));
                return 1;
            }
        }
    }
}
